### ISSUE TITLE
Request new module: Create Client to Site (Cloud) VPN Module 

### ISSUE THREAD

**Issue by Sivasaivm** [cloud-native-toolkit/automation-modules#198] opened 2022-01-25 08:56 UTC
**Related user story**
Provide the issue number for the user story related to this request - 571

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
aws

**What is the purpose of the module?**
Create Client to Site (Cloud) VPN Module for AWS Connectivity.

**What is the category of the module?**
network,infrastructure & util

**Comment by seansund** [comment] 2022-01-27 14:08
@Sivasaivm Isn't this a duplicate of https://github.com/cloud-native-toolkit/automation-modules/issues/196 ?

**Closed** 2022-02-04 14:56 UTC
Labels: new_module
